image: node:18

stages:
  - install
  - test

cache: &node_modules_cache
  key:
    files:
      - package-lock.json
      - package.json
  paths:
    - node_modules/
  policy: pull

Install Dependencies:
  stage: install
  cache:
    - <<: *node_modules_cache
      policy: pull-push
  script:
    - npm ci

Test:
  stage: test
  cache:
    - <<: *node_modules_cache
  variables:
    NODE_ENV: "test"
    MAINNET_RPC_URL: "https://eth-mainnet.g.alchemy.com/v2/S6IYJbKIcQfuc45punUEsYXFbrQKtNrE"
  script:
    - rm -rf ./reports
    - npx hardhat node &
    - npx hardhat test
